#----------------------------------------
# Twinkl Fastlane Pipeline SPM
# Copyright Twinkl Limited 2004
# Created By Josh Robbins (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
#----------------------------------------

# Set Development Platform
default_platform(:ios)

# Create Global Mutable Variables
PACKAGE_NAME = 'NetworkMonitoringPackageTwinkl-Package'

#----------------------------------------
# Dependency Installation
# Setup Base Dependencies
#----------------------------------------

# Setup Base Dependencies On Your Machine
desc "☁️  Installs Base Dependencies For Our Devs."
lane :setupBaseDependenciesOnMachine do
  sh "chmod +x twinklIOSConfiguration.sh"
  sh "./twinklIOSConfiguration.sh"
  UI.success("🫠 Base Dependencies Configured.")
end

# Setup Base Dependencies On CI
desc "☁️  Installs Base Dependencies For The CI."
lane :setupBaseDependenciesCI do
  sh "chmod +x twinklIOSConfigurationCI.sh"
  sh "./twinklIOSConfigurationCI.sh"
  UI.success("🫠 Base Dependencies Configured.")
end

#----------------
#  Tests
# Runs Unit Tests
#----------------

desc "☁️  Runs Unit Tests"
lane :run_unit_tests do

 spm(
  command: "test",
  simulator: "macosx"
)

    
end
